// Generated by CoffeeScript 1.4.0
var express, host, http, plex, port;

express = require('express');

plex = require('plex');

http = require('http');

host = 'localhost';

port = 10101;

module.exports = {
  start: function() {
    var app, server;
    app = express();
    server = http.createServer(app);
    server.listen(10101, host, function() {
      return console.log('listening @ %s:%s', server.address().address, server.address().port);
    });
    return plex.start({
      listen: {
        adaptor: 'socket.io',
        server: server
      }
    });
  }
};
